# Generated by Django 5.0.1 on 2024-01-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.AddField(
            model_name='orders',
            name='booking_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_INR',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_money',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
