# Generated by Django 5.0.1 on 2024-02-02 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_orders_payment_id_orders_signature_id_orders_status_and_more'),
        ('myadmin', '0025_remove_booking_booked_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.venue'),
        ),
    ]
