# Generated by Django 5.0.1 on 2024-01-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_alter_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_date_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_date_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_period',
            field=models.IntegerField(null=True),
        ),
    ]
