# Generated by Django 5.0.1 on 2024-01-29 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_booking_booked_date_from_booking_booked_date_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(verbose_name=datetime.date(2024, 1, 29)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(verbose_name=datetime.time(14, 14, 45, 829295)),
        ),
    ]
