# Generated by Django 5.0.1 on 2024-01-30 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_rename_image_venue_pf_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueimage',
            name='venue',
        ),
        migrations.AddField(
            model_name='venue',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='myadmin.venueimage'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(verbose_name=datetime.time(21, 18, 28, 526411)),
        ),
    ]
