# Generated by Django 5.0.1 on 2024-01-30 16:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_remove_venueimage_venue_venue_gallery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='gallery',
        ),
        migrations.AddField(
            model_name='venueimage',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.venue'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(verbose_name=datetime.time(22, 13, 48, 393523)),
        ),
        migrations.AlterField(
            model_name='venueimage',
            name='gallery',
            field=models.ImageField(blank=True, null=True, upload_to='venue_img'),
        ),
    ]
