# Generated by Django 5.0.1 on 2024-01-31 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0016_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(verbose_name=datetime.time(15, 58, 49, 548162)),
        ),
    ]
