# Generated by Django 5.0.1 on 2024-01-31 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0020_alter_booking_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(verbose_name=datetime.time(21, 47, 9, 566330)),
        ),
    ]
