# Generated by Django 5.0.1 on 2024-02-02 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0025_remove_booking_booked_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateField(default=datetime.time(12, 33, 13, 312652)),
        ),
    ]
